In [ ]:
#!pip install spacy
#!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz --no-deps

In [1]:

import pandas as pd
import spacy 
import en_core_web_sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:

xl = pd.ExcelFile("WAR Excel.xlsx")
#xl.sheet_names
df = xl.parse("WAR 2")
df.head()

Saving WAR Excel.xlsx to WAR Excel.xlsx

                         Created By  ...                                       Path
0  Jackson Cheryl D NGA-APA USA CTR  ...  org/A_Internal/a_tools/Lists/Analysis_WAR
1  Jackson Cheryl D NGA-APA USA CTR  ...  org/A_Internal/a_tools/Lists/Analysis_WAR
2  Jackson Cheryl D NGA-APA USA CTR  ...  org/A_Internal/a_tools/Lists/Analysis_WAR
3  Jackson Cheryl D NGA-APA USA CTR  ...  org/A_Internal/a_tools/Lists/Analysis_WAR
4  Jackson Cheryl D NGA-APA USA CTR  ...  org/A_Internal/a_tools/Lists/Analysis_WAR

[5 rows x 15 columns]

In [ ]:
# from nltk.tokenize import sent_tokenize, word_tokenize
# from nltk.stem import WordNetLemmatizer

# porter=PorterStemmer()
# wordnet_lemmatizer = WordNetLemmatizer()



# def stemer_lemmatizer(sentence):
#     token_words=word_tokenize(sentence.lower())
#     token_words
#     stem_sentence=[]
#     for word in token_words:
#       stem_sentence.append(wordnet_lemmatizer.lemmatize(word))
#       stem_sentence.append(" ")
#     return "".join(stem_sentence)




# print(df['Activity Details'][0])
# print("Stemmed sentence")
# x=stemer_lemmatizer(df['Activity Details'][0])
# print(x)

(U//FOUO) On April 2nd, 2020, the NGA Support Team to Department of State (DoS) and U.S. AID, met with the Deputy Assistant Secretary of the DoS Bureau of Conflict, Stabilization, and Operations to discuss ways forward for a visit to NCE that was postponed by COVID-19 and to present to NGA details on the funding short fall for the Armed Conflict Location and Event Data (ACLED) Project. NGA last provided funding to the ACLED program in Jan 2019. Without additional funding for FY20, ACLED will reduce support starting in July and will only cover events in Africa and parts of the Middle East. AOQ is working with GILOB, SF, and A leadership to see if NGA is able to assist in funding a portion of the budget shortfall to keep this critical data source in operation.
Stemmed sentence
( u//fouo ) on april 2nd , 2020 , the nga support team to department of state ( do ) and u.s. aid , met with the deputy assistant secretary of the do bureau of conflict , stabilization , and operation to discus way forward for a visit to nce that wa postponed by covid-19 and to present to nga detail on the funding short fall for the armed conflict location and event data ( acled ) project . nga last provided funding to the acled program in jan 2019. without additional funding for fy20 , acled will reduce support starting in july and will only cover event in africa and part of the middle east . aoq is working with gilob , sf , and a leadership to see if nga is able to assist in funding a portion of the budget shortfall to keep this critical data source in operation .

In [4]:
#import en_core_web_sm
nlp = en_core_web_sm.load()   

GPE_submission_dict = {}
LOC_submission_dict = {}
PERSON_submission_dict = {}
ORG_submission_dict = {}
WORK_OF_ART_submission_dict = {}
EVENT_submission_dict = {}
LAW_submission_dict = {}
FAC_submission_dict = {}
LANGUAGE_submission_dict = {}

for a_details, a_date in zip(df['Activity Details'], df['Activity Date']):
  #lem_detaila = stemer_lemmatizer(a_details)

  doc = nlp(a_details.lower())

  for ent in doc.ents:
      #print(ent.text, ent.start_char, ent.end_char, ent.label_) 
      if ent.label_ == 'GPE':
        if ent.text.strip() == 'us' or ent.text.strip()  == 'u.s.' or ent.text.strip()  == 'the united states' or ent.text.strip()  == 'america':
          GPE_submission_dict[a_date] = 'United States'
        else:
          GPE_submission_dict[a_date] = ent.text.strip().capitalize()
      if ent.label_ == 'LOC':
        LOC_submission_dict[a_date] = ent.text.strip().capitalize()
      if ent.label_ == 'PERSON':
        PERSON_submission_dict[a_date]  = ent.text.strip().capitalize()
      if ent.label_ == 'WORK_OF_ART':
        WORK_OF_ART_submission_dict[a_date]  = ent.text.strip().capitalize()    
      if ent.label_ == 'ORG':
        ORG_submission_dict[a_date]  = ent.text.strip().capitalize() 
      if ent.label_ == 'EVENT':
        EVENT_submission_dict[a_date]  = ent.text.strip().capitalize() 
      if ent.label_ == 'LAW':
        LAW_submission_dict[a_date]  = ent.text.strip().capitalize() 
      if ent.label_ == 'FAC':
        FAC_submission_dict[a_date]  = ent.text.strip().capitalize() 
      if ent.label_ == 'LANGUAGE':
        LANGUAGE_submission_dict[a_date]  = ent.text.strip().capitalize() 

GPE_DF = pd.DataFrame(list(GPE_submission_dict.items()),columns = ['Date','GPE'])
GPE_DF.to_csv('GPE_DF.csv', index=False)

LOC_DF = pd.DataFrame(list(LOC_submission_dict.items()),columns = ['Date','LOC'])
LOC_DF.to_csv('LOC_DF.csv', index=False)

PERSON_DF = pd.DataFrame(list(PERSON_submission_dict.items()),columns = ['Date','PERSON'])
PERSON_DF.to_csv('PERSON_DF.csv', index=False)

ORG_DF = pd.DataFrame(list(ORG_submission_dict.items()),columns = ['Date','ORG'])
ORG_DF.to_csv('ORG_DF.csv', index=False)

WORK_OF_ART_DF = pd.DataFrame(list(WORK_OF_ART_submission_dict.items()),columns = ['Date','WORK_OF_ART'])
WORK_OF_ART_DF.to_csv('WORK_OF_ART_DF.csv', index=False)

EVENT_DF = pd.DataFrame(list(EVENT_submission_dict.items()),columns = ['Date','EVENT'])
EVENT_DF.to_csv('EVENT_DF.csv', index=False)

LAW_DF = pd.DataFrame(list(LAW_submission_dict.items()),columns = ['Date','LAW'])
LAW_DF.to_csv('LAW_DF.csv', index=False)

In [5]:
GPE_DF

          Date            GPE
0   2020-04-02       Thailand
1   2020-04-10  United States
2   2020-04-13          Aoggg
3   2020-04-14       Cerebrum
4   2020-04-16     Washington
..         ...            ...
106 2020-10-29       L3harris
107 2020-11-03           Iran
108 2020-11-13       Valverde
109 2020-11-16  United States
110 2020-11-09          Atscp

[111 rows x 2 columns]

In [6]:
LOC_DF

         Date                     LOC
0  2020-04-02         The middle east
1  2020-04-13  The western hemisphere
2  2020-04-14               Caribbean
3  2020-04-16    The hasakah province
4  2020-04-17                  Africa
5  2020-04-23  The western hemisphere
6  2020-04-24  The western hemisphere
7  2020-04-29                  Africa
8  2020-05-05  The western hemisphere
9  2020-04-27                   Earth
10 2020-05-01                   Earth
11 2020-05-15               Caribbean
12 2020-04-06         Central america
13 2020-05-19            Asia-pacific
14 2020-05-21           Latin america
15 2020-05-06                  Africa
16 2020-05-22     The south china sea
17 2020-05-18  The western hemisphere
18 2020-06-05  The western hemisphere
19 2020-05-20  The western hemisphere
20 2020-05-27                  Africa
21 2020-04-20                  Europe
22 2020-06-10               East asia
23 2020-06-08  The western hemisphere
24 2020-06-16                Covid-19
25 2020-06-19   The arabian peninsula
26 2020-06-12         The middle east
27 2020-06-17                  Africa
28 2020-07-02          The nile basin
29 2020-07-01           South america
30 2020-06-18           South america
31 2020-07-13  The western hemisphere
32 2020-07-10                 Eurasia
33 2020-08-04   The galapagos islands
34 2020-08-18                    Nile
35 2020-08-26     The eastern pacific
36 2020-09-02               Peninsula
37 2020-09-01           Miyako strait
38 2020-08-27      Western hemisphere
39 2020-09-09                   Earth
40 2020-09-15                  Africa
41 2020-09-17                  Arctic
42 2020-10-02                  Africa
43 2020-10-09         Hurricane delta
44 2020-10-26               East asia
45        NaT           Latin america

In [7]:
ORG_DF

          Date                       ORG
0   2020-04-02                       Aot
1   2020-04-09    Apmm data science team
2   2020-04-10                       Aow
3   2020-04-13              Dean strevel
4   2020-04-14                       Aot
..         ...                       ...
137 2020-11-18                       Atc
138 2020-11-10                Penn state
139 2020-11-20                       Aya
140 2020-11-09                       Pmr
141 2020-11-19  Mitigates usg assistance

[142 rows x 2 columns]

In [8]:
WORK_OF_ART_DF

        Date                                        WORK_OF_ART
0        NaT                                           Covid-19
1 2020-04-17                                           Covid-19
2 2020-04-13                                           Covid-19
3 2020-06-16                                           Covid-19
4 2020-07-09  White fragility: why it’s so hard for white pe...
5 2020-07-31                    Https://go.intelink.gov/mzff9ld
6 2020-09-18                       Clip and ship” functionality

In [10]:
PERSON_DF

          Date           PERSON
0   2020-04-09            207th
1   2020-04-10      Shawn ayers
2   2020-04-13      Starr - aox
3   2020-04-14   Charlotte owen
4   2020-04-07   Charlotte owen
..         ...              ...
140 2020-11-18  Justin procopio
141 2020-11-10    Thomas thorpe
142 2020-11-20              Aot
143 2020-11-09   Steven ramberg
144 2020-11-05      Jacob graul

[145 rows x 2 columns]

In [11]:
EVENT_DF

         Date                                      EVENT
0  2020-04-17  The venezuela humanitarian crisis project
1  2020-05-20                         The lecture series
2  2020-05-06          The venezuela humanitarian crisis
3  2020-04-27                           Hurricane season
4  2020-06-04                           Hurricane season
5  2020-06-08                           Hurricane season
6  2020-06-03               Woolpert annual crada report
7  2020-06-16                   The 202 hurricane season
8  2020-07-08                               Lidar series
9  2020-08-18                            Plenary session
10 2020-08-27                            Hurricane laura
11 2020-09-03                               World war ii
12 2020-09-11                            Hurricane laura
13 2020-09-22                            Plenary session
14 2020-10-09                         Hurricane landfall
15 2020-10-20                   Geospatial gateway forum